services:
  xavia-ota-adminer:
    image: adminer:5.3.0
    container_name: xavia-ota-adminer
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    ports:
      - 8082:8080
    networks:
      - xavia_default
    env_file: ../../.env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.adminer.rule=Host(`adminer.${DOMAIN}`)'
      - 'traefik.http.routers.adminer.entrypoints=websecure'
      - 'traefik.http.services.adminer.loadbalancer.server.port=8080'

networks:
  xavia_default:
    external: true
