services:
  xavia-ota-traefik:
    image: traefik:v3.6.7
    container_name: xavia-ota-traefik
    restart: always
    env_file: ../.env
    security_opt:
      - no-new-privileges:true
    command:
      # Disable Dashboard & API
      - '--api.dashboard=false'
      - '--api.insecure=false'
      - '--ping=true'
      # Docker Provider
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=xavia_default'
      # Entrypoints
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      # HTTP to HTTPS Redirect
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      # SSL (Let's Encrypt)
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=${SSL_EMAIL}'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      # Access Log Configuration
      - '--accesslog=true'
      - '--accesslog.format=json'
      - '--accesslog.filepath=/var/log/traefik/access.json'
    labels:
      - 'traefik.enable=false'
      - 'traefik.http.routers.traefik-dash.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.traefik-dash.entrypoints=websecure'
      - 'traefik.http.routers.traefik-dash.tls.certresolver=myresolver'
      - 'traefik.http.routers.traefik-dash.tls=true'
      - 'traefik.http.services.traefik-dash.loadbalancer.server.port=8080'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - /var/log/traefik:/var/log/traefik
    networks:
      - xavia_default
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  xavia_default:
    external: true
