# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "expo-update-opentofu-tfstate-us-east-1"
    dynamodb_table = "expo-update-opentofu-lock-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    profile        = "expo-update-opentofu"
    region         = "us-east-1"
  }
}
