# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "us-east-1"
  profile = "expo-update-opentofu"

  default_tags {
    tags = { "Environment" : "Prod", "ManagedBy" : "Terragrunt", "Owner" : "DevOps-Team", "Project" : "Expo-Update", "TofuVersion" : "1.11.5" }
  }
}
