services:
  xavia-ota-nextjs:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:${APP_VERSION}
    container_name: xavia-ota-nextjs
    ports:
      - '3000:3000'
    env_file: ../../.env
    restart: always
    networks:
      - xavia_default
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://127.0.0.1:3000/api/health']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextjs.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.services.nextjs.loadbalancer.server.port=3000'
      - 'traefik.http.routers.nextjs.entrypoints=websecure'
      - 'traefik.http.routers.nextjs.tls=true'
      - 'traefik.http.routers.nextjs.tls.certresolver=myresolver'

networks:
  xavia_default:
    external: true
